// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://setjegcismdzcejsgqsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNldGplZ2Npc21kemNlanNncXN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTQzOTQsImV4cCI6MjA2ODkzMDM5NH0.-cY35DeU0xChVJG1fkxjs2TAFWAlfdmtUZwaiYAZxpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});